-- Representative educational content, not user history.
-- Generated with dart run tool/generate_sample_seed.dart
begin;
insert into public.categories(id, name, description, sort_order) values ('english', 'English', 'Grammar and vocabulary', 0) on conflict (id) do nothing;
insert into public.topics(id, category_id, name) values ('english_grammar', 'english', 'grammar') on conflict (id) do nothing;
insert into public.questions(id, category_id, topic_id, question_text, question_type, correct_option_id, explanation, difficulty, points, sort_order) values ('en_1', 'english', 'english_grammar', 'She ___ to university every day.', 'multiple_choice', 'en_1_1', 'With she, he or it, the Present Simple verb normally takes -s or -es.', 'easy', 1, 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('en_1_0', 'en_1', 'go', 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('en_1_1', 'en_1', 'goes', 1) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('en_1_2', 'en_1', 'going', 2) on conflict (id) do nothing;
insert into public.topics(id, category_id, name) values ('english_vocabulary', 'english', 'vocabulary') on conflict (id) do nothing;
insert into public.questions(id, category_id, topic_id, question_text, question_type, correct_option_id, explanation, difficulty, points, sort_order) values ('en_2', 'english', 'english_vocabulary', '“Quick” and “fast” can have similar meanings.', 'true_false', 'en_2_0', 'Both words can describe something moving or happening at high speed.', 'easy', 1, 1) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('en_2_0', 'en_2', 'True', 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('en_2_1', 'en_2', 'False', 1) on conflict (id) do nothing;
insert into public.questions(id, category_id, topic_id, question_text, question_type, correct_option_id, explanation, difficulty, points, sort_order) values ('en_3', 'english', 'english_grammar', 'Choose the correct sentence.', 'multiple_choice', 'en_3_2', 'The pronoun they takes are in the present tense.', 'easy', 2, 2) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('en_3_0', 'en_3', 'They is ready.', 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('en_3_1', 'en_3', 'They am ready.', 1) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('en_3_2', 'en_3', 'They are ready.', 2) on conflict (id) do nothing;
insert into public.categories(id, name, description, sort_order) values ('kazakh', 'Kazakh', 'Everyday words and grammar', 1) on conflict (id) do nothing;
insert into public.topics(id, category_id, name) values ('kazakh_vocabulary', 'kazakh', 'vocabulary') on conflict (id) do nothing;
insert into public.questions(id, category_id, topic_id, question_text, question_type, correct_option_id, explanation, difficulty, points, sort_order) values ('kk_1', 'kazakh', 'kazakh_vocabulary', '«Кітап» сөзінің ағылшынша аудармасы қандай?', 'multiple_choice', 'kk_1_0', '«Кітап» ағылшын тілінде book деп аударылады.', 'easy', 1, 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('kk_1_0', 'kk_1', 'Book', 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('kk_1_1', 'kk_1', 'Window', 1) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('kk_1_2', 'kk_1', 'Water', 2) on conflict (id) do nothing;
insert into public.topics(id, category_id, name) values ('kazakh_grammar', 'kazakh', 'grammar') on conflict (id) do nothing;
insert into public.questions(id, category_id, topic_id, question_text, question_type, correct_option_id, explanation, difficulty, points, sort_order) values ('kk_2', 'kazakh', 'kazakh_grammar', '«Балалар» сөзі көпше түрде берілген.', 'true_false', 'kk_2_0', 'Бала сөзіне -лар көптік жалғауы жалғанған.', 'easy', 1, 1) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('kk_2_0', 'kk_2', 'Дұрыс', 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('kk_2_1', 'kk_2', 'Бұрыс', 1) on conflict (id) do nothing;
insert into public.questions(id, category_id, topic_id, question_text, question_type, correct_option_id, explanation, difficulty, points, sort_order) values ('kk_3', 'kazakh', 'kazakh_vocabulary', '«Үлкен» сөзінің антонимін таңдаңыз.', 'multiple_choice', 'kk_3_1', 'Үлкен және кіші — қарама-қарсы мағыналы сөздер.', 'easy', 2, 2) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('kk_3_0', 'kk_3', 'Ұзын', 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('kk_3_1', 'kk_3', 'Кіші', 1) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('kk_3_2', 'kk_3', 'Жақсы', 2) on conflict (id) do nothing;
insert into public.categories(id, name, description, sort_order) values ('russian', 'Russian', 'Everyday words and grammar', 2) on conflict (id) do nothing;
insert into public.topics(id, category_id, name) values ('russian_grammar', 'russian', 'grammar') on conflict (id) do nothing;
insert into public.questions(id, category_id, topic_id, question_text, question_type, correct_option_id, explanation, difficulty, points, sort_order) values ('ru_1', 'russian', 'russian_grammar', 'Выберите форму множественного числа слова «книга».', 'multiple_choice', 'ru_1_1', 'Книги — форма именительного падежа множественного числа.', 'easy', 1, 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('ru_1_0', 'ru_1', 'Книгой', 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('ru_1_1', 'ru_1', 'Книги', 1) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('ru_1_2', 'ru_1', 'Книгу', 2) on conflict (id) do nothing;
insert into public.topics(id, category_id, name) values ('russian_vocabulary', 'russian', 'vocabulary') on conflict (id) do nothing;
insert into public.questions(id, category_id, topic_id, question_text, question_type, correct_option_id, explanation, difficulty, points, sort_order) values ('ru_2', 'russian', 'russian_vocabulary', 'Слова «горячий» и «холодный» — синонимы.', 'true_false', 'ru_2_1', 'Эти слова имеют противоположные значения: это антонимы.', 'easy', 1, 1) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('ru_2_0', 'ru_2', 'Верно', 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('ru_2_1', 'ru_2', 'Неверно', 1) on conflict (id) do nothing;
insert into public.questions(id, category_id, topic_id, question_text, question_type, correct_option_id, explanation, difficulty, points, sort_order) values ('ru_3', 'russian', 'russian_grammar', 'Вставьте слово: «Она ___ письмо вчера».', 'multiple_choice', 'ru_3_0', 'Местоимение «она» требует формы прошедшего времени женского рода.', 'easy', 2, 2) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('ru_3_0', 'ru_3', 'написала', 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('ru_3_1', 'ru_3', 'написал', 1) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('ru_3_2', 'ru_3', 'написали', 2) on conflict (id) do nothing;
insert into public.categories(id, name, description, sort_order) values ('logic', 'Logic & Reasoning', 'Patterns and reasoning', 3) on conflict (id) do nothing;
insert into public.topics(id, category_id, name) values ('logic_patterns', 'logic', 'patterns') on conflict (id) do nothing;
insert into public.questions(id, category_id, topic_id, question_text, question_type, correct_option_id, explanation, difficulty, points, sort_order) values ('logic_1', 'logic', 'logic_patterns', 'What comes next: 2, 4, 8, 16, ...?', 'multiple_choice', 'logic_1_2', 'Each number is twice the previous number.', 'easy', 1, 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('logic_1_0', 'logic_1', '18', 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('logic_1_1', 'logic_1', '24', 1) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('logic_1_2', 'logic_1', '32', 2) on conflict (id) do nothing;
insert into public.topics(id, category_id, name) values ('logic_deduction', 'logic', 'deduction') on conflict (id) do nothing;
insert into public.questions(id, category_id, topic_id, question_text, question_type, correct_option_id, explanation, difficulty, points, sort_order) values ('logic_2', 'logic', 'logic_deduction', 'All cats are mammals. Therefore, all mammals are cats.', 'true_false', 'logic_2_1', 'The first statement does not imply its reverse; other mammals can exist.', 'easy', 1, 1) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('logic_2_0', 'logic_2', 'True', 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('logic_2_1', 'logic_2', 'False', 1) on conflict (id) do nothing;
insert into public.topics(id, category_id, name) values ('logic_numerical', 'logic', 'numerical') on conflict (id) do nothing;
insert into public.questions(id, category_id, topic_id, question_text, question_type, correct_option_id, explanation, difficulty, points, sort_order) values ('logic_3', 'logic', 'logic_numerical', 'A box has 3 rows of 4 counters. How many counters are there?', 'multiple_choice', 'logic_3_1', 'Three equal rows of four contain 3 × 4 = 12 counters.', 'easy', 2, 2) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('logic_3_0', 'logic_3', '7', 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('logic_3_1', 'logic_3', '12', 1) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('logic_3_2', 'logic_3', '16', 2) on conflict (id) do nothing;
insert into public.categories(id, name, description, sort_order) values ('programming', 'Programming', 'Dart fundamentals', 4) on conflict (id) do nothing;
insert into public.topics(id, category_id, name) values ('programming_variables', 'programming', 'variables') on conflict (id) do nothing;
insert into public.questions(id, category_id, topic_id, question_text, question_type, correct_option_id, explanation, difficulty, points, sort_order) values ('dart_1', 'programming', 'programming_variables', 'In Dart, what does final mean for a variable?', 'multiple_choice', 'dart_1_0', 'A final variable can be assigned once. This does not automatically make a referenced collection immutable.', 'easy', 1, 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('dart_1_0', 'dart_1', 'It can be assigned only once.', 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('dart_1_1', 'dart_1', 'It must contain an integer.', 1) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('dart_1_2', 'dart_1', 'It is always globally visible.', 2) on conflict (id) do nothing;
insert into public.topics(id, category_id, name) values ('programming_null_safety', 'programming', 'null safety') on conflict (id) do nothing;
insert into public.questions(id, category_id, topic_id, question_text, question_type, correct_option_id, explanation, difficulty, points, sort_order) values ('dart_2', 'programming', 'programming_null_safety', 'A Dart variable declared as String? can contain null.', 'true_false', 'dart_2_0', 'The question mark marks a nullable type.', 'easy', 1, 1) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('dart_2_0', 'dart_2', 'True', 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('dart_2_1', 'dart_2', 'False', 1) on conflict (id) do nothing;
insert into public.topics(id, category_id, name) values ('programming_operators', 'programming', 'operators') on conflict (id) do nothing;
insert into public.questions(id, category_id, topic_id, question_text, question_type, correct_option_id, explanation, difficulty, points, sort_order) values ('dart_3', 'programming', 'programming_operators', 'What does this Dart expression evaluate to?

7 ~/ 2', 'multiple_choice', 'dart_3_1', 'The ~/ operator performs truncating division, so 7 ~/ 2 is 3.', 'easy', 2, 2) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('dart_3_0', 'dart_3', '3.5', 0) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('dart_3_1', 'dart_3', '3', 1) on conflict (id) do nothing;
insert into public.question_options(id, question_id, option_text, sort_order) values ('dart_3_2', 'dart_3', '4', 2) on conflict (id) do nothing;
commit;
